version: "3.9"

services:
  persistence:
    build:
      context: ./Persistence
    expose:
      - "8080"
  level:
    build:
      context: ./Level
    expose:
      - "8080"
  view:
    build: ./View
    ports:
      - "8080:8080"
    depends_on:
      - level
      - persistence
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"