version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: bind
        source: ./database-data
        target: /database-data
  persistence:
    build:
      context: ./Persistence
    expose:
      - "8080"
  level:
    build:
      context: ./Level
    expose:
      - "8080"
  view:
    build: ./View
    ports:
      - "8080:8080"
    depends_on:
      - level
      - persistence
    stdin_open: true
    environment:
      DISPLAY: host.docker.internal:0