version: "3.9"

services:
  level:
    build:
      context: ./Level
    ports:
      - "8081:8081"
  persistence:
    build:
      context: ./Persistence
    ports:
      - "8080:8080"
  view:
    build: ./View
    ports:
      - "8082:8082"
    depends_on:
      - level
      - persistence
    environment:
      DISPLAY: unix$DISPLAY
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"